name: sola_mpd

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      # To unlock the advanced search features, uncomment the following line.
      # Please read the README.md for more information.
      # args:
      #   LAINBOW_ENDPOINT: "http://your.lainbow.endpoint:port"
    image: sola_mpd_prebuilt:latest
    container_name: sola_mpd
    volumes:
      - db:/app/packages/backend/db
    environment:
      - USER=${USER}
    ### Network Configuration Options ###
    # Option 1: Host network mode (Recommended for better compatibility)
    network_mode: host

    # Option 2: Bridge network mode
    # If using bridge mode, comment out network_mode: host above and uncomment the following:
    # network_mode: bridge
    # ports:
    #   - 3000:3000
    #   # Or use a custom port:
    #   # - 8080:3000
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    
    restart: always
    # Alternatively, use "no" for manual restart
    # restart: no

  # subsonic:
  #   build:
  #     context: .
  #     dockerfile: plugins/subsonic/docker/Dockerfile
  #   image: sola_mpd_subsonic:latest
  #   container_name: sola_mpd_subsonic
  #   environment:
  #     - USER=${USER}
  #   ### Network Configuration Options ###
  #   # Option 1: Host network mode (Recommended for better compatibility)
  #   network_mode: host

  #   # Option 2: Bridge network mode
  #   # If using bridge mode, comment out network_mode: host above and uncomment the following:
  #   # network_mode: bridge
  #   # ports:
  #   #   - 3001:3001
  #   #   # Or use a custom port:
  #   #   # - 8081:3001
    
  #   restart: always
  #   # Alternatively, use "no" for manual restart
  #   # restart: no

volumes:
  db:
