// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file plugin/plugin_wrapper.proto (package sola, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { PluginExecuteRequest, PluginExecuteResponse, PluginRegisterRequest, PluginRegisterResponse } from "./plugin_pb.js";
import { file_plugin_plugin } from "./plugin_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file plugin/plugin_wrapper.proto.
 */
export const file_plugin_plugin_wrapper: GenFile = /*@__PURE__*/
  fileDesc("ChtwbHVnaW4vcGx1Z2luX3dyYXBwZXIucHJvdG8SBHNvbGEiTAocUGx1Z2luUmVnaXN0ZXJSZXF1ZXN0V3JhcHBlchIsCgdyZXF1ZXN0GAEgASgLMhsuc29sYS5QbHVnaW5SZWdpc3RlclJlcXVlc3QibAodUGx1Z2luUmVnaXN0ZXJSZXNwb25zZVdyYXBwZXISMAoIcmVzcG9uc2UYASABKAsyHC5zb2xhLlBsdWdpblJlZ2lzdGVyUmVzcG9uc2VIABIPCgVlcnJvchgCIAEoCUgAQggKBnJlc3VsdCJiChtQbHVnaW5FeGVjdXRlUmVxdWVzdFdyYXBwZXISKwoHcmVxdWVzdBgBIAEoCzIaLnNvbGEuUGx1Z2luRXhlY3V0ZVJlcXVlc3QSFgoOY2FsbGJhY2tfZXZlbnQYAiABKAkifgocUGx1Z2luRXhlY3V0ZVJlc3BvbnNlV3JhcHBlchIvCghyZXNwb25zZRgBIAEoCzIbLnNvbGEuUGx1Z2luRXhlY3V0ZVJlc3BvbnNlSAASDwoFZXJyb3IYAiABKAlIABISCghjb21wbGV0ZRgDIAEoCEgAQggKBnJlc3VsdGIGcHJvdG8z", [file_plugin_plugin]);

/**
 * @generated from message sola.PluginRegisterRequestWrapper
 */
export type PluginRegisterRequestWrapper = Message<"sola.PluginRegisterRequestWrapper"> & {
  /**
   * @generated from field: sola.PluginRegisterRequest request = 1;
   */
  request?: PluginRegisterRequest;
};

/**
 * Describes the message sola.PluginRegisterRequestWrapper.
 * Use `create(PluginRegisterRequestWrapperSchema)` to create a new message.
 */
export const PluginRegisterRequestWrapperSchema: GenMessage<PluginRegisterRequestWrapper> = /*@__PURE__*/
  messageDesc(file_plugin_plugin_wrapper, 0);

/**
 * @generated from message sola.PluginRegisterResponseWrapper
 */
export type PluginRegisterResponseWrapper = Message<"sola.PluginRegisterResponseWrapper"> & {
  /**
   * @generated from oneof sola.PluginRegisterResponseWrapper.result
   */
  result: {
    /**
     * @generated from field: sola.PluginRegisterResponse response = 1;
     */
    value: PluginRegisterResponse;
    case: "response";
  } | {
    /**
     * @generated from field: string error = 2;
     */
    value: string;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message sola.PluginRegisterResponseWrapper.
 * Use `create(PluginRegisterResponseWrapperSchema)` to create a new message.
 */
export const PluginRegisterResponseWrapperSchema: GenMessage<PluginRegisterResponseWrapper> = /*@__PURE__*/
  messageDesc(file_plugin_plugin_wrapper, 1);

/**
 * @generated from message sola.PluginExecuteRequestWrapper
 */
export type PluginExecuteRequestWrapper = Message<"sola.PluginExecuteRequestWrapper"> & {
  /**
   * @generated from field: sola.PluginExecuteRequest request = 1;
   */
  request?: PluginExecuteRequest;

  /**
   * @generated from field: string callback_event = 2;
   */
  callbackEvent: string;
};

/**
 * Describes the message sola.PluginExecuteRequestWrapper.
 * Use `create(PluginExecuteRequestWrapperSchema)` to create a new message.
 */
export const PluginExecuteRequestWrapperSchema: GenMessage<PluginExecuteRequestWrapper> = /*@__PURE__*/
  messageDesc(file_plugin_plugin_wrapper, 2);

/**
 * @generated from message sola.PluginExecuteResponseWrapper
 */
export type PluginExecuteResponseWrapper = Message<"sola.PluginExecuteResponseWrapper"> & {
  /**
   * @generated from oneof sola.PluginExecuteResponseWrapper.result
   */
  result: {
    /**
     * @generated from field: sola.PluginExecuteResponse response = 1;
     */
    value: PluginExecuteResponse;
    case: "response";
  } | {
    /**
     * @generated from field: string error = 2;
     */
    value: string;
    case: "error";
  } | {
    /**
     * @generated from field: bool complete = 3;
     */
    value: boolean;
    case: "complete";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message sola.PluginExecuteResponseWrapper.
 * Use `create(PluginExecuteResponseWrapperSchema)` to create a new message.
 */
export const PluginExecuteResponseWrapperSchema: GenMessage<PluginExecuteResponseWrapper> = /*@__PURE__*/
  messageDesc(file_plugin_plugin_wrapper, 3);

