// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file plugin/plugin_service.proto (package sola, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PluginExecuteRequest, PluginExecuteResponse, PluginRegisterRequest, PluginRegisterResponse } from "./plugin_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service sola.PluginService
 */
export const PluginService = {
  typeName: "sola.PluginService",
  methods: {
    /**
     * @generated from rpc sola.PluginService.Register
     */
    register: {
      name: "Register",
      I: PluginRegisterRequest,
      O: PluginRegisterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sola.PluginService.Execute
     */
    execute: {
      name: "Execute",
      I: PluginExecuteRequest,
      O: PluginExecuteResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

