// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file plugin/plugin_service.proto (package sola, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { PluginExecuteRequestSchema, PluginExecuteResponseSchema, PluginRegisterRequestSchema, PluginRegisterResponseSchema } from "./plugin_pb.js";
import { file_plugin_plugin } from "./plugin_pb.js";

/**
 * Describes the file plugin/plugin_service.proto.
 */
export const file_plugin_plugin_service: GenFile = /*@__PURE__*/
  fileDesc("ChtwbHVnaW4vcGx1Z2luX3NlcnZpY2UucHJvdG8SBHNvbGEyoAEKDVBsdWdpblNlcnZpY2USRwoIUmVnaXN0ZXISGy5zb2xhLlBsdWdpblJlZ2lzdGVyUmVxdWVzdBocLnNvbGEuUGx1Z2luUmVnaXN0ZXJSZXNwb25zZSIAEkYKB0V4ZWN1dGUSGi5zb2xhLlBsdWdpbkV4ZWN1dGVSZXF1ZXN0Ghsuc29sYS5QbHVnaW5FeGVjdXRlUmVzcG9uc2UiADABYgZwcm90bzM", [file_plugin_plugin]);

/**
 * @generated from service sola.PluginService
 */
export const PluginService: GenService<{
  /**
   * @generated from rpc sola.PluginService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof PluginRegisterRequestSchema;
    output: typeof PluginRegisterResponseSchema;
  },
  /**
   * @generated from rpc sola.PluginService.Execute
   */
  execute: {
    methodKind: "server_streaming";
    input: typeof PluginExecuteRequestSchema;
    output: typeof PluginExecuteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_plugin_plugin_service, 0);

