// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=js"
// @generated from file mpd/mpd_event.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mpd/mpd_event.proto.
 */
export const file_mpd_mpd_event: GenFile = /*@__PURE__*/
  fileDesc("ChNtcGQvbXBkX2V2ZW50LnByb3RvIrwBCghNcGRFdmVudBInCgpldmVudF90eXBlGAEgASgOMhMuTXBkRXZlbnQuRXZlbnRUeXBlIoYBCglFdmVudFR5cGUSCwoHVU5LTk9XThAAEgwKCERBVEFCQVNFEAESDAoIUExBWUxJU1QQAhIOCgpQTEFZX1FVRVVFEAMSCQoFTUlYRVIQBBILCgdPUFRJT05TEAUSCgoGUExBWUVSEAYSEAoMRElTQ09OTkVDVEVEEAcSCgoGVVBEQVRFEAhiBnByb3RvMw");

/**
 * @generated from message MpdEvent
 */
export type MpdEvent = Message<"MpdEvent"> & {
  /**
   * @generated from field: MpdEvent.EventType event_type = 1;
   */
  eventType: MpdEvent_EventType;
};

/**
 * Describes the message MpdEvent.
 * Use `create(MpdEventSchema)` to create a new message.
 */
export const MpdEventSchema: GenMessage<MpdEvent> = /*@__PURE__*/
  messageDesc(file_mpd_mpd_event, 0);

/**
 * @generated from enum MpdEvent.EventType
 */
export enum MpdEvent_EventType {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: DATABASE = 1;
   */
  DATABASE = 1,

  /**
   * @generated from enum value: PLAYLIST = 2;
   */
  PLAYLIST = 2,

  /**
   * @generated from enum value: PLAY_QUEUE = 3;
   */
  PLAY_QUEUE = 3,

  /**
   * @generated from enum value: MIXER = 4;
   */
  MIXER = 4,

  /**
   * @generated from enum value: OPTIONS = 5;
   */
  OPTIONS = 5,

  /**
   * @generated from enum value: PLAYER = 6;
   */
  PLAYER = 6,

  /**
   * @generated from enum value: DISCONNECTED = 7;
   */
  DISCONNECTED = 7,

  /**
   * @generated from enum value: UPDATE = 8;
   */
  UPDATE = 8,
}

/**
 * Describes the enum MpdEvent.EventType.
 */
export const MpdEvent_EventTypeSchema: GenEnum<MpdEvent_EventType> = /*@__PURE__*/
  enumDesc(file_mpd_mpd_event, 0, 0);

