// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=js"
// @generated from file mpd/mpd_output.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mpd/mpd_output.proto.
 */
export const file_mpd_mpd_output: GenFile = /*@__PURE__*/
  fileDesc("ChRtcGQvbXBkX291dHB1dC5wcm90byJPCg9NcGRPdXRwdXREZXZpY2USCgoCaWQYASABKAUSDAoEbmFtZRgCIAEoCRIOCgZwbHVnaW4YAyABKAkSEgoKaXNfZW5hYmxlZBgEIAEoCGIGcHJvdG8z");

/**
 * @generated from message MpdOutputDevice
 */
export type MpdOutputDevice = Message<"MpdOutputDevice"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string plugin = 3;
   */
  plugin: string;

  /**
   * @generated from field: bool is_enabled = 4;
   */
  isEnabled: boolean;
};

/**
 * Describes the message MpdOutputDevice.
 * Use `create(MpdOutputDeviceSchema)` to create a new message.
 */
export const MpdOutputDeviceSchema: GenMessage<MpdOutputDevice> = /*@__PURE__*/
  messageDesc(file_mpd_mpd_output, 0);

