// @generated by protoc-gen-es v2.6.3 with parameter "target=ts,import_extension=js"
// @generated from file recently_added.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Song_MetadataTag } from "./song_pb.js";
import { file_song } from "./song_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file recently_added.proto.
 */
export const file_recently_added: GenFile = /*@__PURE__*/
  fileDesc("ChRyZWNlbnRseV9hZGRlZC5wcm90byI1ChNSZWNlbnRseUFkZGVkRmlsdGVyEh4KA3RhZxgBIAEoDjIRLlNvbmcuTWV0YWRhdGFUYWciOwoSUmVjZW50bHlBZGRlZFN0YXRlEiUKB2ZpbHRlcnMYASADKAsyFC5SZWNlbnRseUFkZGVkRmlsdGVyYgZwcm90bzM", [file_song]);

/**
 * @generated from message RecentlyAddedFilter
 */
export type RecentlyAddedFilter = Message<"RecentlyAddedFilter"> & {
  /**
   * @generated from field: Song.MetadataTag tag = 1;
   */
  tag: Song_MetadataTag;
};

/**
 * Describes the message RecentlyAddedFilter.
 * Use `create(RecentlyAddedFilterSchema)` to create a new message.
 */
export const RecentlyAddedFilterSchema: GenMessage<RecentlyAddedFilter> = /*@__PURE__*/
  messageDesc(file_recently_added, 0);

/**
 * @generated from message RecentlyAddedState
 */
export type RecentlyAddedState = Message<"RecentlyAddedState"> & {
  /**
   * @generated from field: repeated RecentlyAddedFilter filters = 1;
   */
  filters: RecentlyAddedFilter[];
};

/**
 * Describes the message RecentlyAddedState.
 * Use `create(RecentlyAddedStateSchema)` to create a new message.
 */
export const RecentlyAddedStateSchema: GenMessage<RecentlyAddedState> = /*@__PURE__*/
  messageDesc(file_recently_added, 1);

