// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file song.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { FloatValue, Int32Value, StringValue, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file song.proto.
 */
export const file_song: GenFile = /*@__PURE__*/
  fileDesc("Cgpzb25nLnByb3RvIpgBCgtBdWRpb0Zvcm1hdBInCghlbmNvZGluZxgBIAEoDjIVLkF1ZGlvRm9ybWF0LkVuY29kaW5nEhUKDXNhbXBsaW5nX3JhdGUYAiABKA0SDAoEYml0cxgDIAEoDRIQCghjaGFubmVscxgEIAEoDSIpCghFbmNvZGluZxILCgdVTktOT1dOEAASBwoDUENNEAESBwoDRFNEEAIi+QQKBFNvbmcSDAoEcGF0aBgBIAEoCRIlCghtZXRhZGF0YRgCIAMoCzITLlNvbmcuTWV0YWRhdGFFbnRyeRINCgVpbmRleBgDIAEoBRpECg1NZXRhZGF0YUVudHJ5EgsKA2tleRgBIAEoCRIiCgV2YWx1ZRgCIAEoCzITLlNvbmcuTWV0YWRhdGFWYWx1ZToCOAEahQIKDU1ldGFkYXRhVmFsdWUSNAoMc3RyaW5nX3ZhbHVlGAIgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlSAASMAoJaW50X3ZhbHVlGAMgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkludDMyVmFsdWVIABIyCgtmbG9hdF92YWx1ZRgEIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5GbG9hdFZhbHVlSAASHgoGZm9ybWF0GAUgASgLMgwuQXVkaW9Gb3JtYXRIABIvCgl0aW1lc3RhbXAYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSABCBwoFdmFsdWUi3gEKC01ldGFkYXRhVGFnEgsKB1VOS05PV04QABIJCgVUSVRMRRABEgoKBkFSVElTVBACEhAKDEFMQlVNX0FSVElTVBADEgkKBUFMQlVNEAQSCQoFR0VOUkUQBRIMCghDT01QT1NFUhAGEgkKBVRSQUNLEAcSCAoERElTQxAIEggKBERBVEUQCRIMCghEVVJBVElPThAKEgoKBkZPUk1BVBALEg4KClVQREFURURfQVQQDBIGCgJJRBANEgwKCFBPU0lUSU9OEA4SCwoHQ09NTUVOVBAPEgkKBUxBQkVMEBAiIAoIU29uZ0xpc3QSFAoFc29uZ3MYASADKAsyBS5Tb25nYgZwcm90bzM", [file_google_protobuf_timestamp, file_google_protobuf_wrappers]);

/**
 * @generated from message AudioFormat
 */
export type AudioFormat = Message<"AudioFormat"> & {
  /**
   * @generated from field: AudioFormat.Encoding encoding = 1;
   */
  encoding: AudioFormat_Encoding;

  /**
   * @generated from field: uint32 sampling_rate = 2;
   */
  samplingRate: number;

  /**
   * @generated from field: uint32 bits = 3;
   */
  bits: number;

  /**
   * @generated from field: uint32 channels = 4;
   */
  channels: number;
};

/**
 * Describes the message AudioFormat.
 * Use `create(AudioFormatSchema)` to create a new message.
 */
export const AudioFormatSchema: GenMessage<AudioFormat> = /*@__PURE__*/
  messageDesc(file_song, 0);

/**
 * @generated from enum AudioFormat.Encoding
 */
export enum AudioFormat_Encoding {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: PCM = 1;
   */
  PCM = 1,

  /**
   * @generated from enum value: DSD = 2;
   */
  DSD = 2,
}

/**
 * Describes the enum AudioFormat.Encoding.
 */
export const AudioFormat_EncodingSchema: GenEnum<AudioFormat_Encoding> = /*@__PURE__*/
  enumDesc(file_song, 0, 0);

/**
 * @generated from message Song
 */
export type Song = Message<"Song"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: map<string, Song.MetadataValue> metadata = 2;
   */
  metadata: { [key: string]: Song_MetadataValue };

  /**
   * index can be used for the application specific usage. This is different
   * from MetadataTag.POSITION which is managed by MPD.
   *
   * @generated from field: int32 index = 3;
   */
  index: number;
};

/**
 * Describes the message Song.
 * Use `create(SongSchema)` to create a new message.
 */
export const SongSchema: GenMessage<Song> = /*@__PURE__*/
  messageDesc(file_song, 1);

/**
 * @generated from message Song.MetadataValue
 */
export type Song_MetadataValue = Message<"Song.MetadataValue"> & {
  /**
   * @generated from oneof Song.MetadataValue.value
   */
  value: {
    /**
     * @generated from field: google.protobuf.StringValue string_value = 2;
     */
    value: StringValue;
    case: "stringValue";
  } | {
    /**
     * @generated from field: google.protobuf.Int32Value int_value = 3;
     */
    value: Int32Value;
    case: "intValue";
  } | {
    /**
     * @generated from field: google.protobuf.FloatValue float_value = 4;
     */
    value: FloatValue;
    case: "floatValue";
  } | {
    /**
     * @generated from field: AudioFormat format = 5;
     */
    value: AudioFormat;
    case: "format";
  } | {
    /**
     * @generated from field: google.protobuf.Timestamp timestamp = 6;
     */
    value: Timestamp;
    case: "timestamp";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message Song.MetadataValue.
 * Use `create(Song_MetadataValueSchema)` to create a new message.
 */
export const Song_MetadataValueSchema: GenMessage<Song_MetadataValue> = /*@__PURE__*/
  messageDesc(file_song, 1, 0);

/**
 * @generated from enum Song.MetadataTag
 */
export enum Song_MetadataTag {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: TITLE = 1;
   */
  TITLE = 1,

  /**
   * @generated from enum value: ARTIST = 2;
   */
  ARTIST = 2,

  /**
   * @generated from enum value: ALBUM_ARTIST = 3;
   */
  ALBUM_ARTIST = 3,

  /**
   * @generated from enum value: ALBUM = 4;
   */
  ALBUM = 4,

  /**
   * @generated from enum value: GENRE = 5;
   */
  GENRE = 5,

  /**
   * @generated from enum value: COMPOSER = 6;
   */
  COMPOSER = 6,

  /**
   * @generated from enum value: TRACK = 7;
   */
  TRACK = 7,

  /**
   * @generated from enum value: DISC = 8;
   */
  DISC = 8,

  /**
   * @generated from enum value: DATE = 9;
   */
  DATE = 9,

  /**
   * @generated from enum value: DURATION = 10;
   */
  DURATION = 10,

  /**
   * @generated from enum value: FORMAT = 11;
   */
  FORMAT = 11,

  /**
   * @generated from enum value: UPDATED_AT = 12;
   */
  UPDATED_AT = 12,

  /**
   * @generated from enum value: ID = 13;
   */
  ID = 13,

  /**
   * @generated from enum value: POSITION = 14;
   */
  POSITION = 14,

  /**
   * @generated from enum value: COMMENT = 15;
   */
  COMMENT = 15,

  /**
   * @generated from enum value: LABEL = 16;
   */
  LABEL = 16,
}

/**
 * Describes the enum Song.MetadataTag.
 */
export const Song_MetadataTagSchema: GenEnum<Song_MetadataTag> = /*@__PURE__*/
  enumDesc(file_song, 1, 0);

/**
 * @generated from message SongList
 */
export type SongList = Message<"SongList"> & {
  /**
   * @generated from field: repeated Song songs = 1;
   */
  songs: Song[];
};

/**
 * Describes the message SongList.
 * Use `create(SongListSchema)` to create a new message.
 */
export const SongListSchema: GenMessage<SongList> = /*@__PURE__*/
  messageDesc(file_song, 2);

