// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file mpd/mpd_profile.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message MpdProfile
 */
export class MpdProfile extends Message<MpdProfile> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: string host = 2;
   */
  host = "";

  /**
   * @generated from field: uint32 port = 3;
   */
  port = 0;

  constructor(data?: PartialMessage<MpdProfile>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "MpdProfile";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "host", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "port", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MpdProfile {
    return new MpdProfile().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MpdProfile {
    return new MpdProfile().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MpdProfile {
    return new MpdProfile().fromJsonString(jsonString, options);
  }

  static equals(a: MpdProfile | PlainMessage<MpdProfile> | undefined, b: MpdProfile | PlainMessage<MpdProfile> | undefined): boolean {
    return proto3.util.equals(MpdProfile, a, b);
  }
}

/**
 * @generated from message MpdProfileState
 */
export class MpdProfileState extends Message<MpdProfileState> {
  /**
   * @generated from field: MpdProfile current_profile = 1;
   */
  currentProfile?: MpdProfile;

  /**
   * @generated from field: repeated MpdProfile profiles = 2;
   */
  profiles: MpdProfile[] = [];

  constructor(data?: PartialMessage<MpdProfileState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "MpdProfileState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "current_profile", kind: "message", T: MpdProfile },
    { no: 2, name: "profiles", kind: "message", T: MpdProfile, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MpdProfileState {
    return new MpdProfileState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MpdProfileState {
    return new MpdProfileState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MpdProfileState {
    return new MpdProfileState().fromJsonString(jsonString, options);
  }

  static equals(a: MpdProfileState | PlainMessage<MpdProfileState> | undefined, b: MpdProfileState | PlainMessage<MpdProfileState> | undefined): boolean {
    return proto3.util.equals(MpdProfileState, a, b);
  }
}

