// @generated by protoc-gen-es v2.6.3 with parameter "target=ts,import_extension=js"
// @generated from file mpd/mpd_stats.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mpd/mpd_stats.proto.
 */
export const file_mpd_mpd_stats: GenFile = /*@__PURE__*/
  fileDesc("ChNtcGQvbXBkX3N0YXRzLnByb3RvIskBCghNcGRTdGF0cxIPCgd2ZXJzaW9uGAEgASgJEhUKDWFydGlzdHNfY291bnQYAiABKAUSFAoMYWxidW1zX2NvdW50GAMgASgFEhMKC3NvbmdzX2NvdW50GAQgASgFEg4KBnVwdGltZRgFIAEoBRIWCg50b3RhbF9wbGF5dGltZRgGIAEoBRIwCgxsYXN0X3VwZGF0ZWQYByABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhAKCHBsYXl0aW1lGAggASgFYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message MpdStats
 */
export type MpdStats = Message<"MpdStats"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * @generated from field: int32 artists_count = 2;
   */
  artistsCount: number;

  /**
   * @generated from field: int32 albums_count = 3;
   */
  albumsCount: number;

  /**
   * @generated from field: int32 songs_count = 4;
   */
  songsCount: number;

  /**
   * @generated from field: int32 uptime = 5;
   */
  uptime: number;

  /**
   * @generated from field: int32 total_playtime = 6;
   */
  totalPlaytime: number;

  /**
   * @generated from field: google.protobuf.Timestamp last_updated = 7;
   */
  lastUpdated?: Timestamp;

  /**
   * @generated from field: int32 playtime = 8;
   */
  playtime: number;
};

/**
 * Describes the message MpdStats.
 * Use `create(MpdStatsSchema)` to create a new message.
 */
export const MpdStatsSchema: GenMessage<MpdStats> = /*@__PURE__*/
  messageDesc(file_mpd_mpd_stats, 0);

