// @generated by protoc-gen-es v2.6.3 with parameter "target=ts,import_extension=js"
// @generated from file mpd/mpd_profile.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mpd/mpd_profile.proto.
 */
export const file_mpd_mpd_profile: GenFile = /*@__PURE__*/
  fileDesc("ChVtcGQvbXBkX3Byb2ZpbGUucHJvdG8iNgoKTXBkUHJvZmlsZRIMCgRuYW1lGAEgASgJEgwKBGhvc3QYAiABKAkSDAoEcG9ydBgDIAEoDSJWCg9NcGRQcm9maWxlU3RhdGUSJAoPY3VycmVudF9wcm9maWxlGAEgASgLMgsuTXBkUHJvZmlsZRIdCghwcm9maWxlcxgCIAMoCzILLk1wZFByb2ZpbGViBnByb3RvMw");

/**
 * @generated from message MpdProfile
 */
export type MpdProfile = Message<"MpdProfile"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string host = 2;
   */
  host: string;

  /**
   * @generated from field: uint32 port = 3;
   */
  port: number;
};

/**
 * Describes the message MpdProfile.
 * Use `create(MpdProfileSchema)` to create a new message.
 */
export const MpdProfileSchema: GenMessage<MpdProfile> = /*@__PURE__*/
  messageDesc(file_mpd_mpd_profile, 0);

/**
 * @generated from message MpdProfileState
 */
export type MpdProfileState = Message<"MpdProfileState"> & {
  /**
   * @generated from field: MpdProfile current_profile = 1;
   */
  currentProfile?: MpdProfile;

  /**
   * @generated from field: repeated MpdProfile profiles = 2;
   */
  profiles: MpdProfile[];
};

/**
 * Describes the message MpdProfileState.
 * Use `create(MpdProfileStateSchema)` to create a new message.
 */
export const MpdProfileStateSchema: GenMessage<MpdProfileState> = /*@__PURE__*/
  messageDesc(file_mpd_mpd_profile, 1);

