// @generated by protoc-gen-es v1.8.0 with parameter "target=ts"
// @generated from file mpd/mpd_stats.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message MpdStats
 */
export class MpdStats extends Message<MpdStats> {
  /**
   * @generated from field: string version = 1;
   */
  version = "";

  /**
   * @generated from field: int32 artists_count = 2;
   */
  artistsCount = 0;

  /**
   * @generated from field: int32 albums_count = 3;
   */
  albumsCount = 0;

  /**
   * @generated from field: int32 songs_count = 4;
   */
  songsCount = 0;

  /**
   * @generated from field: int32 uptime = 5;
   */
  uptime = 0;

  /**
   * @generated from field: int32 total_playtime = 6;
   */
  totalPlaytime = 0;

  /**
   * @generated from field: google.protobuf.Timestamp last_updated = 7;
   */
  lastUpdated?: Timestamp;

  /**
   * @generated from field: int32 playtime = 8;
   */
  playtime = 0;

  constructor(data?: PartialMessage<MpdStats>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "MpdStats";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "artists_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "albums_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "songs_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "uptime", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "total_playtime", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "last_updated", kind: "message", T: Timestamp },
    { no: 8, name: "playtime", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MpdStats {
    return new MpdStats().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MpdStats {
    return new MpdStats().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MpdStats {
    return new MpdStats().fromJsonString(jsonString, options);
  }

  static equals(a: MpdStats | PlainMessage<MpdStats> | undefined, b: MpdStats | PlainMessage<MpdStats> | undefined): boolean {
    return proto3.util.equals(MpdStats, a, b);
  }
}

