// @generated by protoc-gen-es v2.6.3 with parameter "target=ts,import_extension=js"
// @generated from file mpd/mpd_player.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { AudioFormat } from "../song_pb.js";
import { file_song } from "../song_pb.js";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mpd/mpd_player.proto.
 */
export const file_mpd_mpd_player: GenFile = /*@__PURE__*/
  fileDesc("ChRtcGQvbXBkX3BsYXllci5wcm90byLgAwoPTXBkUGxheWVyU3RhdHVzEhEKCWlzX3JlcGVhdBgBIAEoCBIRCglpc19yYW5kb20YAiABKAgSEQoJaXNfc2luZ2xlGAMgASgIEhIKCmlzX2NvbnN1bWUYBCABKAgSGQoRcGxheV9xdWV1ZV9sZW5ndGgYBSABKAUSNgoOcGxheWJhY2tfc3RhdGUYBiABKA4yHi5NcGRQbGF5ZXJTdGF0dXMuUGxheWJhY2tTdGF0ZRIMCgRzb25nGAcgASgFEg8KB3NvbmdfaWQYCCABKAUSEQoJbmV4dF9zb25nGAkgASgFEhQKDG5leHRfc29uZ19pZBgKIAEoBRIUCgdlbGFwc2VkGAsgASgCSACIAQESFQoIZHVyYXRpb24YDCABKAJIAYgBARIUCgdiaXRyYXRlGA0gASgFSAKIAQESIgoMYXVkaW9fZm9ybWF0GA4gASgLMgwuQXVkaW9Gb3JtYXQSHAoUaXNfZGF0YWJhc2VfdXBkYXRpbmcYECABKAgiOwoNUGxheWJhY2tTdGF0ZRILCgdVTktOT1dOEAASCAoEUExBWRABEggKBFNUT1AQAhIJCgVQQVVTRRADQgoKCF9lbGFwc2VkQgsKCV9kdXJhdGlvbkIKCghfYml0cmF0ZSI+Cg9NcGRQbGF5ZXJWb2x1bWUSKwoGdm9sdW1lGAEgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkludDMyVmFsdWViBnByb3RvMw", [file_song, file_google_protobuf_wrappers]);

/**
 * @generated from message MpdPlayerStatus
 */
export type MpdPlayerStatus = Message<"MpdPlayerStatus"> & {
  /**
   * @generated from field: bool is_repeat = 1;
   */
  isRepeat: boolean;

  /**
   * @generated from field: bool is_random = 2;
   */
  isRandom: boolean;

  /**
   * @generated from field: bool is_single = 3;
   */
  isSingle: boolean;

  /**
   * @generated from field: bool is_consume = 4;
   */
  isConsume: boolean;

  /**
   * @generated from field: int32 play_queue_length = 5;
   */
  playQueueLength: number;

  /**
   * @generated from field: MpdPlayerStatus.PlaybackState playback_state = 6;
   */
  playbackState: MpdPlayerStatus_PlaybackState;

  /**
   * @generated from field: int32 song = 7;
   */
  song: number;

  /**
   * @generated from field: int32 song_id = 8;
   */
  songId: number;

  /**
   * @generated from field: int32 next_song = 9;
   */
  nextSong: number;

  /**
   * @generated from field: int32 next_song_id = 10;
   */
  nextSongId: number;

  /**
   * @generated from field: optional float elapsed = 11;
   */
  elapsed?: number;

  /**
   * @generated from field: optional float duration = 12;
   */
  duration?: number;

  /**
   * @generated from field: optional int32 bitrate = 13;
   */
  bitrate?: number;

  /**
   * @generated from field: AudioFormat audio_format = 14;
   */
  audioFormat?: AudioFormat;

  /**
   * @generated from field: bool is_database_updating = 16;
   */
  isDatabaseUpdating: boolean;
};

/**
 * Describes the message MpdPlayerStatus.
 * Use `create(MpdPlayerStatusSchema)` to create a new message.
 */
export const MpdPlayerStatusSchema: GenMessage<MpdPlayerStatus> = /*@__PURE__*/
  messageDesc(file_mpd_mpd_player, 0);

/**
 * @generated from enum MpdPlayerStatus.PlaybackState
 */
export enum MpdPlayerStatus_PlaybackState {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: PLAY = 1;
   */
  PLAY = 1,

  /**
   * @generated from enum value: STOP = 2;
   */
  STOP = 2,

  /**
   * @generated from enum value: PAUSE = 3;
   */
  PAUSE = 3,
}

/**
 * Describes the enum MpdPlayerStatus.PlaybackState.
 */
export const MpdPlayerStatus_PlaybackStateSchema: GenEnum<MpdPlayerStatus_PlaybackState> = /*@__PURE__*/
  enumDesc(file_mpd_mpd_player, 0, 0);

/**
 * @generated from message MpdPlayerVolume
 */
export type MpdPlayerVolume = Message<"MpdPlayerVolume"> & {
  /**
   * @generated from field: google.protobuf.Int32Value volume = 1;
   */
  volume?: number;
};

/**
 * Describes the message MpdPlayerVolume.
 * Use `create(MpdPlayerVolumeSchema)` to create a new message.
 */
export const MpdPlayerVolumeSchema: GenMessage<MpdPlayerVolume> = /*@__PURE__*/
  messageDesc(file_mpd_mpd_player, 1);

