name: Create tag on version bump

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  version-tag:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'version-bump')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Get version from package.json
        run: echo version=$(node -p "require('./package.json').version") >> $GITHUB_ENV

      - name: Create GitHub tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ env.version }}
          git push origin v${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
