// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=js"
// @generated from file browser.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Song_MetadataTag, Song_MetadataValue } from "./song_pb.js";
import { file_song } from "./song_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file browser.proto.
 */
export const file_browser: GenFile = /*@__PURE__*/
  fileDesc("Cg1icm93c2VyLnByb3RvIoQBCg1Ccm93c2VyRmlsdGVyEh4KA3RhZxgBIAEoDjIRLlNvbmcuTWV0YWRhdGFUYWcSLAoPc2VsZWN0ZWRfdmFsdWVzGAIgAygLMhMuU29uZy5NZXRhZGF0YVZhbHVlEg0KBW9yZGVyGAMgASgFEhYKDnNlbGVjdGVkX29yZGVyGAQgASgFIi8KDEJyb3dzZXJTdGF0ZRIfCgdmaWx0ZXJzGAEgAygLMg4uQnJvd3NlckZpbHRlcmIGcHJvdG8z", [file_song]);

/**
 * @generated from message BrowserFilter
 */
export type BrowserFilter = Message<"BrowserFilter"> & {
  /**
   * @generated from field: Song.MetadataTag tag = 1;
   */
  tag: Song_MetadataTag;

  /**
   * @generated from field: repeated Song.MetadataValue selected_values = 2;
   */
  selectedValues: Song_MetadataValue[];

  /**
   * @generated from field: int32 order = 3;
   */
  order: number;

  /**
   * @generated from field: int32 selected_order = 4;
   */
  selectedOrder: number;
};

/**
 * Describes the message BrowserFilter.
 * Use `create(BrowserFilterSchema)` to create a new message.
 */
export const BrowserFilterSchema: GenMessage<BrowserFilter> = /*@__PURE__*/
  messageDesc(file_browser, 0);

/**
 * @generated from message BrowserState
 */
export type BrowserState = Message<"BrowserState"> & {
  /**
   * @generated from field: repeated BrowserFilter filters = 1;
   */
  filters: BrowserFilter[];
};

/**
 * Describes the message BrowserState.
 * Use `create(BrowserStateSchema)` to create a new message.
 */
export const BrowserStateSchema: GenMessage<BrowserState> = /*@__PURE__*/
  messageDesc(file_browser, 1);

