// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file browser.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Song_MetadataTag, Song_MetadataValue } from "./song_pb.js";
import { file_song } from "./song_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file browser.proto.
 */
export const file_browser: GenFile = /*@__PURE__*/
  fileDesc("Cg1icm93c2VyLnByb3RvIpABCg1Ccm93c2VyRmlsdGVyEh4KA3RhZxgBIAEoDjIRLlNvbmcuTWV0YWRhdGFUYWcSMAoPc2VsZWN0ZWRfdmFsdWVzGAIgAygLMhMuU29uZy5NZXRhZGF0YVZhbHVlQgIYARIRCgVvcmRlchgDIAEoBUICGAESGgoOc2VsZWN0ZWRfb3JkZXIYBCABKAVCAhgBInMKDEJyb3dzZXJTdGF0ZRIjCgdmaWx0ZXJzGAEgAygLMg4uQnJvd3NlckZpbHRlckICGAESFgoOc2NoZW1hX3ZlcnNpb24YAiABKA0SJgoLZmlsdGVyX3RhZ3MYAyADKA4yES5Tb25nLk1ldGFkYXRhVGFnYgZwcm90bzM", [file_song]);

/**
 * @generated from message BrowserFilter
 */
export type BrowserFilter = Message<"BrowserFilter"> & {
  /**
   * @generated from field: Song.MetadataTag tag = 1;
   */
  tag: Song_MetadataTag;

  /**
   * @generated from field: repeated Song.MetadataValue selected_values = 2 [deprecated = true];
   * @deprecated
   */
  selectedValues: Song_MetadataValue[];

  /**
   * @generated from field: int32 order = 3 [deprecated = true];
   * @deprecated
   */
  order: number;

  /**
   * @generated from field: int32 selected_order = 4 [deprecated = true];
   * @deprecated
   */
  selectedOrder: number;
};

/**
 * Describes the message BrowserFilter.
 * Use `create(BrowserFilterSchema)` to create a new message.
 */
export const BrowserFilterSchema: GenMessage<BrowserFilter> = /*@__PURE__*/
  messageDesc(file_browser, 0);

/**
 * @generated from message BrowserState
 */
export type BrowserState = Message<"BrowserState"> & {
  /**
   * @generated from field: repeated BrowserFilter filters = 1 [deprecated = true];
   * @deprecated
   */
  filters: BrowserFilter[];

  /**
   * @generated from field: uint32 schema_version = 2;
   */
  schemaVersion: number;

  /**
   * @generated from field: repeated Song.MetadataTag filter_tags = 3;
   */
  filterTags: Song_MetadataTag[];
};

/**
 * Describes the message BrowserState.
 * Use `create(BrowserStateSchema)` to create a new message.
 */
export const BrowserStateSchema: GenMessage<BrowserState> = /*@__PURE__*/
  messageDesc(file_browser, 1);

