// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file recently_added.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Song_MetadataTag } from "./song_pb.js";
import { file_song } from "./song_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file recently_added.proto.
 */
export const file_recently_added: GenFile = /*@__PURE__*/
  fileDesc("ChRyZWNlbnRseV9hZGRlZC5wcm90byI5ChNSZWNlbnRseUFkZGVkRmlsdGVyEiIKA3RhZxgBIAEoDjIRLlNvbmcuTWV0YWRhdGFUYWdCAhgBIn8KElJlY2VudGx5QWRkZWRTdGF0ZRIpCgdmaWx0ZXJzGAEgAygLMhQuUmVjZW50bHlBZGRlZEZpbHRlckICGAESFgoOc2NoZW1hX3ZlcnNpb24YAiABKA0SJgoLZmlsdGVyX3RhZ3MYAyADKA4yES5Tb25nLk1ldGFkYXRhVGFnYgZwcm90bzM", [file_song]);

/**
 * @generated from message RecentlyAddedFilter
 */
export type RecentlyAddedFilter = Message<"RecentlyAddedFilter"> & {
  /**
   * @generated from field: Song.MetadataTag tag = 1 [deprecated = true];
   * @deprecated
   */
  tag: Song_MetadataTag;
};

/**
 * Describes the message RecentlyAddedFilter.
 * Use `create(RecentlyAddedFilterSchema)` to create a new message.
 */
export const RecentlyAddedFilterSchema: GenMessage<RecentlyAddedFilter> = /*@__PURE__*/
  messageDesc(file_recently_added, 0);

/**
 * @generated from message RecentlyAddedState
 */
export type RecentlyAddedState = Message<"RecentlyAddedState"> & {
  /**
   * @generated from field: repeated RecentlyAddedFilter filters = 1 [deprecated = true];
   * @deprecated
   */
  filters: RecentlyAddedFilter[];

  /**
   * @generated from field: uint32 schema_version = 2;
   */
  schemaVersion: number;

  /**
   * @generated from field: repeated Song.MetadataTag filter_tags = 3;
   */
  filterTags: Song_MetadataTag[];
};

/**
 * Describes the message RecentlyAddedState.
 * Use `create(RecentlyAddedStateSchema)` to create a new message.
 */
export const RecentlyAddedStateSchema: GenMessage<RecentlyAddedState> = /*@__PURE__*/
  messageDesc(file_recently_added, 1);

