// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file song_table.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Song_MetadataTag } from "./song_pb.js";
import { file_song } from "./song_pb.js";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file song_table.proto.
 */
export const file_song_table: GenFile = /*@__PURE__*/
  fileDesc("ChBzb25nX3RhYmxlLnByb3RvIo8BCg9Tb25nVGFibGVDb2x1bW4SHgoDdGFnGAEgASgOMhEuU29uZy5NZXRhZGF0YVRhZxIbCgpzb3J0X29yZGVyGAIgASgFQgIYAUgAiAEBEhgKDGlzX3NvcnRfZGVzYxgDIAEoCEICGAESFgoKd2lkdGhfZmxleBgEIAEoBUICGAFCDQoLX3NvcnRfb3JkZXIidwoOU29uZ1RhYmxlU3RhdGUSJQoHY29sdW1ucxgBIAMoCzIQLlNvbmdUYWJsZUNvbHVtbkICGAESFgoOc2NoZW1hX3ZlcnNpb24YAiABKA0SJgoLY29sdW1uX3RhZ3MYAyADKA4yES5Tb25nLk1ldGFkYXRhVGFnYgZwcm90bzM", [file_song, file_google_protobuf_wrappers]);

/**
 * @generated from message SongTableColumn
 */
export type SongTableColumn = Message<"SongTableColumn"> & {
  /**
   * @generated from field: Song.MetadataTag tag = 1;
   */
  tag: Song_MetadataTag;

  /**
   * @generated from field: optional int32 sort_order = 2 [deprecated = true];
   * @deprecated
   */
  sortOrder?: number | undefined;

  /**
   * @generated from field: bool is_sort_desc = 3 [deprecated = true];
   * @deprecated
   */
  isSortDesc: boolean;

  /**
   * @generated from field: int32 width_flex = 4 [deprecated = true];
   * @deprecated
   */
  widthFlex: number;
};

/**
 * Describes the message SongTableColumn.
 * Use `create(SongTableColumnSchema)` to create a new message.
 */
export const SongTableColumnSchema: GenMessage<SongTableColumn> = /*@__PURE__*/
  messageDesc(file_song_table, 0);

/**
 * @generated from message SongTableState
 */
export type SongTableState = Message<"SongTableState"> & {
  /**
   * @generated from field: repeated SongTableColumn columns = 1 [deprecated = true];
   * @deprecated
   */
  columns: SongTableColumn[];

  /**
   * @generated from field: uint32 schema_version = 2;
   */
  schemaVersion: number;

  /**
   * @generated from field: repeated Song.MetadataTag column_tags = 3;
   */
  columnTags: Song_MetadataTag[];
};

/**
 * Describes the message SongTableState.
 * Use `create(SongTableStateSchema)` to create a new message.
 */
export const SongTableStateSchema: GenMessage<SongTableState> = /*@__PURE__*/
  messageDesc(file_song_table, 1);

